# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20180212_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber'},
        ),
    ]
